name: CI

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - name: Set Node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12.x
      - run: npm ci
      - run: npm run build
      - name: Unit Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1" # optional: defaults to us-east-1
          SOURCE_DIR: "build" # optional: defaults to entire repository
